### ISSUE TITLE
Neveikia naudotojų rolės

### ISSUE THREAD

**Issue by Giedrius-Kristinaitis** [AbziBzi/ProgramuSistemuTestavimas#1]
**Žingsniai:**
Paspausti "Add role" mygtuką.

**Numatytas rezultatas:**
Programa turi pridėti rolę.

**Gautas rezultatas:**
Paspaudus "Add role" mygtuką programa meta išimtį ir jos neapdoroja.

**Comment by Giedrius-Kristinaitis** [comment]
2020-12-12 00:12 

can still reproduce the issue, please fix it in the next version, my life depends on it, if it is not fixed, my boss will rape me,

thanks, rakesh out

**Comment by Giedrius-Kristinaitis** [comment]
> 2020-12-12 00:12
> 
> can still reproduce the issue, please fix it in the next version, my life depends on it, if it is not fixed, my boss will rape me,
> 
> thanks, rakesh out

ka tu cia nusisneki asile

**Comment by StrikerLTU** [comment]
stale issue 60s

**Comment by Giedrius-Kristinaitis** [comment]
eik nx

**Comment by StrikerLTU** [comment]
Master šakoje naudotojo rolė nebuvo implementuota, klaida sutvarkyta ant PR #2 @Justas-Milisiunas gali peržiūrėti pakeitimus?

**Comment by Justas-Milisiunas** [comment]
Neagliu

**Comment by Giedrius-Kristinaitis** [comment]
> Master šakoje naudotojo rolė nebuvo implementuota, klaida sutvarkyta ant PR #2 @Justas-Milisiunas gali peržiūrėti pakeitimus?

bybys tai ne pirstas

**Comment by Giedrius-Kristinaitis** [comment]
Aciu ponai uz fixa

**Comment by Justas327** [comment]
Jo viskas gerai, gali mergint
